# Generated by Django 4.1.6 on 2023-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_media_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='apps_post_slug_e3c710_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='apps_post_created_85b06e_idx'),
        ),
    ]
