# Generated by Django 4.1.6 on 2023-05-02 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('apps', '0006_notifaication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifaication',
            new_name='Notification',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='apps_notifi_created_5e9842_idx',
            old_name='apps_notifa_created_c6f473_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='apps_notifi_content_0b84d9_idx',
            old_name='apps_notifa_content_69d9b1_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read'], name='apps_notifi_read_578e0e_idx'),
        ),
    ]
