# Generated by Django 4.1.6 on 2023-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_notifaication_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['-created_at'], name='apps_follow_created_544cce_idx'),
        ),
    ]
